# Generated by Django 6.0.5 on 2026-06-04 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaRegistro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(default='No asignado', max_length=200),
        ),
    ]
